# Generated by Django 3.0.7 on 2022-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_doc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_id', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_url', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_url_id', models.CharField(blank=True, max_length=50, null=True)),
                ('team_id', models.CharField(blank=True, max_length=50, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('doc_title', models.CharField(blank=True, max_length=75, null=True)),
                ('doc_text', models.TextField(blank=True, null=True)),
                ('doc_last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_last_active_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
