# Generated by Django 3.0.7 on 2022-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='collaborator_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
