# Generated by Django 3.0.7 on 2022-06-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_docs_collaborator_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='doc_last_viewed_at',
        ),
    ]
