# Generated by Django 3.0.7 on 2020-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='opp_url_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phone_call',
            name='phonecall_url_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
