# Generated by Django 3.0.7 on 2020-12-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201217_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_call',
            name='modified_username',
            field=models.CharField(default='', max_length=75),
        ),
    ]
