# Generated by Django 3.0.7 on 2020-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_phone_call_modified_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='modified_username',
            field=models.CharField(default='', max_length=75),
        ),
    ]
