# Generated by Django 3.0.7 on 2022-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_opportunities_modified_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='qualified_by_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunities',
            name='qualified_by_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
