# Generated by Django 3.0.7 on 2023-11-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20220628_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='opp_amount',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
    ]
