# Generated by Django 3.0.3 on 2020-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user_id', models.CharField(max_length=50)),
                ('case_no', models.CharField(max_length=50)),
                ('casestatus', models.CharField(max_length=50)),
                ('contact_id', models.CharField(max_length=50)),
                ('created_user_id', models.CharField(max_length=50)),
                ('createdtime', models.CharField(max_length=50)),
                ('group_id', models.CharField(max_length=50)),
                ('case_id', models.CharField(max_length=50)),
                ('modifiedby', models.CharField(max_length=50)),
                ('modifiedtime', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('time_spent', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
