# Generated by Django 3.0.3 on 2020-12-02 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_dashboard', '0004_cases_time_spent_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_resolved',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
