# Generated by Django 3.0.3 on 2020-12-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_dashboard', '0005_cases_case_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_resolved',
            field=models.DateTimeField(null=True),
        ),
    ]
