# Generated by Django 3.0.2 on 2020-01-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_scheduled', models.CharField(max_length=50)),
                ('demo_given', models.CharField(max_length=50)),
                ('quote_sent', models.CharField(max_length=50)),
                ('pilot', models.CharField(max_length=50)),
                ('needs_analysis', models.CharField(max_length=50)),
                ('closed_won', models.CharField(max_length=50)),
                ('closed_lost', models.CharField(max_length=50)),
                ('phone_calls', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=75)),
            ],
        ),
    ]
