# Generated by Django 3.0.3 on 2020-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sales_stats_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_calls', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=75)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
