# Generated by Django 3.0.3 on 2020-02-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_phone_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_stats',
            name='phone_calls',
        ),
    ]
