# Generated by Django 3.0.3 on 2020-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_sales_stats_phone_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_calls',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales_stats',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
