# Generated by Django 3.0.3 on 2020-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200224_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_id', models.CharField(max_length=50)),
                ('contact_id', models.CharField(max_length=50)),
                ('opp_no', models.CharField(max_length=50)),
                ('opp_name', models.CharField(max_length=250)),
                ('opp_stage', models.CharField(max_length=50)),
                ('createdtime', models.DateTimeField()),
                ('modifiedtime', models.DateTimeField()),
                ('created_user_id', models.CharField(max_length=50)),
                ('modifiedby', models.CharField(max_length=50)),
                ('assigned_user_id', models.CharField(max_length=50)),
                ('assigned_username', models.CharField(max_length=75)),
                ('assigned_groupname', models.CharField(max_length=75)),
                ('current_stage_entry_time', models.DateTimeField()),
                ('demo_scheduled_changed_at', models.DateTimeField()),
                ('demo_given_changed_at', models.DateTimeField()),
                ('quote_sent_changed_at', models.DateTimeField()),
                ('pilot_changed_at', models.DateTimeField()),
                ('needs_analysis_changed_at', models.DateTimeField()),
                ('closed_lost_changed_at', models.DateTimeField()),
                ('closed_won_changed_at', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
