# Generated by Django 3.0.3 on 2020-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_opportunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='closed_lost_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='closed_won_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='current_stage_entry_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='demo_given_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='demo_scheduled_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='needs_analysis_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='pilot_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='quote_sent_changed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
