# Generated by Django 3.0.3 on 2020-12-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201210_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(null=True)),
                ('modifiedtime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('assigned_user_id', models.CharField(max_length=50)),
                ('created_user_id', models.CharField(max_length=50)),
                ('modified_by', models.CharField(max_length=50)),
                ('assigned_username', models.CharField(max_length=50)),
                ('assigned_groupname', models.CharField(max_length=50)),
                ('phonecall_id', models.CharField(max_length=50)),
                ('call_status', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('total_duration', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('customer_number', models.CharField(max_length=50)),
                ('recording_url', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
