# Generated by Django 3.0.3 on 2020-12-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_phone_call'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone_calls',
        ),
        migrations.DeleteModel(
            name='sales_stats',
        ),
    ]
