# Generated by Django 3.0.7 on 2020-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_cases_case_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='modified_username',
            field=models.CharField(default='', max_length=75),
        ),
    ]
