# Generated by Django 3.0.7 on 2021-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_cases_modified_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='satisfaction_feedback',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='cases',
            name='satisfaction_index',
            field=models.CharField(default='', max_length=50),
        ),
    ]
