# Generated by Django 3.0.7 on 2021-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redmine_issues',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='category_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='custom_field1_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='custom_field2_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='custom_field3_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='done_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='priority_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='project_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='status_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='tracker_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redmine_issues',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
